% gen_test_vectors.m
% Builds K=512 iterative test vectors using xormap_transform.m (the
% MATLAB port of xormap_cpp/xormap.cpp) and writes:
%   test_vectors.mem   - $readmemh-ready hex values, one per line:
%                         seed, then N successive iterations, repeated
%                         per seed block
%   test_params.vh     - Verilog `define K/NUM_SEEDS/STEPS, kept in sync
%                         with this script so the testbench can't drift
%   test_params.hpp    - same constants for the C++ cross-checker
%
% This is the "ground truth" side of the three-way check: MATLAB produces
% the expected sequence here, cpp_check independently recomputes it with
% xormap_cpp and diffs against this file, and tb_xormap_512.v replays the
% same file against the actual generated hardware.

clear all;
clc

this_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(this_dir, '..', 'xormap_matlab'));

K = 512;
NUM_STEPS = 6;

seeds = {};
seeds{end+1} = false(1, K);                 % all-zero
seeds{end+1} = true(1, K);                  % all-one
b = false(1, K); b(1) = true;
seeds{end+1} = b;                           % single bit set (bit 0 / LSB)
b = false(1, K); b(K) = true;
seeds{end+1} = b;                           % single bit set (bit K-1 / MSB)
rng(20260806);
seeds{end+1} = rand(1, K) > 0.5;            % pseudo-random
seeds{end+1} = rand(1, K) > 0.5;            % pseudo-random

NUM_SEEDS = numel(seeds);

mem_path = fullfile(this_dir, 'test_vectors.mem');
fid = fopen(mem_path, 'w');
if fid == -1
    error('Failed to open %s for writing.', mem_path);
end

for si = 1:NUM_SEEDS
    v = seeds{si};
    fprintf(fid, '%s\n', bits_to_hexstr(v));
    for step = 1:NUM_STEPS
        v = xormap_transform(v, K);
        fprintf(fid, '%s\n', bits_to_hexstr(v));
    end
end
fclose(fid);
fprintf('Wrote %s (%d seeds x (1+%d) lines)\n', mem_path, NUM_SEEDS, NUM_STEPS);

vh_path = fullfile(this_dir, 'test_params.vh');
fid = fopen(vh_path, 'w');
fprintf(fid, '// Auto-generated by gen_test_vectors.m. Do not edit by hand.\n');
fprintf(fid, '`define TB_K %d\n', K);
fprintf(fid, '`define TB_NUM_SEEDS %d\n', NUM_SEEDS);
fprintf(fid, '`define TB_NUM_STEPS %d\n', NUM_STEPS);
fclose(fid);
fprintf('Wrote %s\n', vh_path);

hpp_path = fullfile(this_dir, 'test_params.hpp');
fid = fopen(hpp_path, 'w');
fprintf(fid, '// Auto-generated by gen_test_vectors.m. Do not edit by hand.\n');
fprintf(fid, '#ifndef TEST_PARAMS_HPP\n#define TEST_PARAMS_HPP\n\n');
fprintf(fid, 'constexpr std::size_t kK = %d;\n', K);
fprintf(fid, 'constexpr std::size_t kNumSeeds = %d;\n', NUM_SEEDS);
fprintf(fid, 'constexpr std::size_t kNumSteps = %d;\n', NUM_STEPS);
fprintf(fid, '\n#endif\n');
fclose(fid);
fprintf('Wrote %s\n', hpp_path);

function s = bits_to_hexstr(bits)
% Bit 1 = LSB (matches xormap_transform). Returns an MSB-first hex
% string with no leading "0x", exactly numel(bits)/4 digits.
    k = numel(bits);
    nHex = k / 4;
    s = repmat('0', 1, nHex);
    for h = 0:(nHex - 1)
        nibble = 0;
        for b = 0:3
            bitpos = h * 4 + b;  % 0-based bit index
            if bits(bitpos + 1)
                nibble = nibble + bitshift(1, b);
            end
        end
        s(nHex - h) = lower(dec2hex(nibble));
    end
end
