#ifndef XORMAP_HPP
#define XORMAP_HPP

#include <cstddef>
#include <boost/multiprecision/cpp_int.hpp>

namespace xormap {

using Integer = boost::multiprecision::cpp_int;

// Compute the K-bit result generated by Genv_xormap.m.
// K must be greater than 4. Input must be non-negative and fit in K bits.
// Integer has arbitrary width, so this is not limited to 32 or 64 bits.
Integer transform(const Integer& input, std::size_t k);

}  // namespace xormap

#endif
