function analysis_gray()
%ANALYSIS_GRAY Key sensitivity, histogram and PSNR analysis, grayscale.
%   Runs three further tests across every SIPI grayscale image (159, see
%   download_images_all_gray.m) at K = 24:24:384, and writes one CSV and
%   one vector PDF per test into results/:
%
%     key_sensitivity_gray.{csv,pdf}   NPCR/UACI/PSNR between two ciphers
%                                      whose keys differ in ONE bit, plus
%                                      the PSNR of a wrong-key decryption,
%                                      plus a per-bit-position study.
%     histogram_analysis_gray.{csv,pdf}  chi-square uniformity of the
%                                      plain and cipher histograms.
%     psnr_analysis_gray.{csv,pdf}     PSNR(plain, cipher) and the
%                                      round-trip PSNR.
%
%   All three share the same two encryptions per (image, K), so they are
%   computed in ONE pass rather than three -- running them separately
%   would triple the work for identical numbers.
%
%   IS PSNR APPLICABLE HERE? Partly, and it is worth being precise about
%   which part. PSNR(plain, cipher) and PSNR(plain, wrong-key decryption)
%   are meaningful and are reported: both should be LOW (~8-9 dB), the
%   opposite of the compression setting PSNR was designed for. The
%   round-trip PSNR(plain, correct decryption) is exactly +Inf by
%   construction -- this is a pure XOR stream cipher with no quantisation,
%   so it is lossless and MSE is identically zero. It is asserted as a
%   correctness check but carries no tuning information; it can only ever
%   be Inf or a bug.
%
%   A NOTE ON WHAT KEY SENSITIVITY MEANS FOR A LINEAR MAP. xormap_transform
%   is linear over GF(2) and the keystream is generated by iterating it, so
%   with S1 = key1 XOR h(P) and S2 = key2 XOR h(P):
%
%       C1 XOR C2 = KS(S1) XOR KS(S2) = KS(S1 XOR S2) = KS(key1 XOR key2)
%
%   The difference between the two ciphertexts therefore depends ONLY on
%   which key bit was flipped -- not on the image, and not on the key. This
%   script tests that prediction directly (diff_checksum below must be
%   identical across all images at a given K) instead of assuming it, and
%   the bit-position study then characterises every flip position on a
%   single image, which the prediction says is sufficient.

    this_dir = fileparts(mfilename('fullpath'));
    addpath(this_dir);
    addpath(fullfile(this_dir, '..', 'xormap_matlab'));

    img_dir = fullfile(this_dir, 'images');
    results_dir = fullfile(this_dir, 'results');
    if ~exist(results_dir, 'dir')
        mkdir(results_dir);
    end

    manifest_path = fullfile(img_dir, 'manifest_gray.csv');
    if ~exist(manifest_path, 'file')
        error('analysis_gray:noManifest', ...
            'Manifest not found: %s. Run download_images_all_gray.m first.', manifest_path);
    end
    [files, names, vols] = read_manifest(manifest_path, img_dir);

    K_VALUES = 24:24:384;
    FLIP_BIT = 1;              % key bit flipped for the main table (1 = LSB)

    num_images = numel(files);
    [II, KK] = ndgrid(1:num_images, K_VALUES);
    task_img = II(:);
    task_K = KK(:);
    num_tasks = numel(task_img);

    fprintf('%d images x %d K values = %d tasks\n', num_images, numel(K_VALUES), num_tasks);
    start_pool();

    % columns: K, num_pixels, npcr_key, uaci_key, psnr_c1c2,
    %          psnr_plain_wrongkey, chi2_plain, chi2_cipher, chi2_critical,
    %          psnr_plain_cipher, psnr_roundtrip, diff_checksum,
    %          first_differing_byte
    R = zeros(num_tasks, 13);

    t_all = tic;
    parfor idx = 1:num_tasks
        fname = files{task_img(idx)}; %#ok<PFBNS>
        K = task_K(idx);

        plain = imread(fname);
        num_pixels = numel(plain);

        key1 = secret_key(K);
        key2 = key1;
        key2(FLIP_BIT) = ~key2(FLIP_BIT);          % one-bit key change

        [c1, seed1] = xormap_image_encrypt_fast(plain, key1);
        [c2, ~]     = xormap_image_encrypt_fast(plain, key2);

        cipher_diff = bitxor(c1, c2);

        % The keystream is laid out row-major, so the difference must be
        % read row-major too: MATLAB's (:) is column-major, which for
        % images of different widths compares different keystream
        % positions and makes the image-independence check below fail
        % spuriously.
        diff_row = reshape(cipher_diff.', 1, []);
        first_diff = find(diff_row ~= 0, 1, 'first');
        if isempty(first_diff)
            first_diff = 0;                      % ciphertexts identical
        end

        % Wrong-key decryption. XOR algebra gives it for free:
        %   decrypt(C1, S2) = C1 XOR KS(S2) = P XOR KS(S1) XOR KS(S2)
        %                   = P XOR (C1 XOR C2)
        % so no third keystream generation is needed. Task 1 checks that
        % identity against the real decrypt function rather than trusting
        % the algebra silently.
        wrong = bitxor(plain, cipher_diff);
        if idx == 1
            [~, seed2] = xormap_image_encrypt_fast(plain, key2);
            assert(isequal(xormap_image_decrypt(c1, seed2), wrong), ...
                'wrong-key shortcut disagrees with decrypt()');
        end

        % Round trip with the correct seed must be exact.
        recovered = xormap_image_decrypt(c1, seed1);
        assert(isequal(recovered, plain), 'round trip failed for %s K=%d', fname, K);

        [npcr_key, uaci_key] = npcr_uaci(c1, c2);

        [chi2_p, ~, chi2_crit] = chi_square_uniformity(plain);
        chi2_c                 = chi_square_uniformity(c1);

        R(idx, :) = [K, num_pixels, npcr_key, uaci_key, ...
            psnr_db(c1, c2), psnr_db(plain, wrong), ...
            chi2_p, chi2_c, chi2_crit, ...
            psnr_db(plain, c1), psnr_db(plain, recovered), ...
            diff_checksum(diff_row), first_diff];
    end
    fprintf('Main pass finished in %.1f s.\n', toc(t_all));

    % --- the linearity prediction: C1 XOR C2 must not depend on the image
    same_per_K = arrayfun(@(K) numel(unique(R(R(:,1) == K, 12))) == 1, K_VALUES);
    fprintf(['Key-difference independent of image: %d of %d K values ' ...
             '(prediction: all %d).\n'], sum(same_per_K), numel(K_VALUES), numel(K_VALUES));

    % --- per-bit-position study (one image suffices if the above holds)
    B = bit_position_study(files{1}, K_VALUES);

    write_key_sensitivity(results_dir, R, B, names, vols, task_img, K_VALUES, ...
        FLIP_BIT, same_per_K);
    write_histogram(results_dir, R, names, vols, task_img, K_VALUES, files);
    write_psnr(results_dir, R, names, vols, task_img, K_VALUES);
end

% ---------------------------------------------------------------------------

function B = bit_position_study(fname, K_VALUES)
% Flip each of a spread of key-bit positions and measure the resulting
% ciphertext difference. Rows: [K, bit, npcr, uaci, psnr].
    plain = imread(fname);
    rows = {};
    for K = K_VALUES
        bits = unique(round(linspace(1, K, min(K, 24))));
        key1 = secret_key(K);
        c1 = xormap_image_encrypt_fast(plain, key1);
        r = zeros(numel(bits), 5);
        for b = 1:numel(bits)
            key2 = key1;
            key2(bits(b)) = ~key2(bits(b));
            c2 = xormap_image_encrypt_fast(plain, key2);
            [npcr, uaci] = npcr_uaci(c1, c2);
            r(b, :) = [K, bits(b), npcr, uaci, psnr_db(c1, c2)];
        end
        rows{end + 1} = r; %#ok<AGROW>
    end
    B = vertcat(rows{:});
end

function v = diff_checksum(diff_row)
% Cheap order-sensitive checksum of the leading bytes of a difference
% image, which MUST already be in row-major (keystream) order -- enough to
% tell "identical" from "different" across images of different sizes.
    d = double(diff_row(:));
    n = min(numel(d), 4096);
    v = mod(sum(d(1:n) .* (1:n).'), 2^31);   % both columns: dot product, not outer
end

% ---------------------------------------------------------------------------

function write_key_sensitivity(results_dir, R, B, names, vols, task_img, ...
                               K_VALUES, flip_bit, same_per_K)
    csv = fullfile(results_dir, 'key_sensitivity_gray.csv');
    fid = fopen(csv, 'w');
    fprintf(fid, ['image,volume,K,num_pixels,flipped_key_bit,npcr_key,uaci_key,' ...
        'psnr_cipher_pair_db,psnr_plain_wrongkey_db,first_differing_byte,' ...
        'key_diff_checksum\n']);
    for r = 1:size(R, 1)
        fprintf(fid, '%s,%s,%d,%d,%d,%.6f,%.6f,%.4f,%.4f,%d,%d\n', ...
            names{task_img(r)}, vols{task_img(r)}, R(r,1), R(r,2), flip_bit, ...
            R(r,3), R(r,4), R(r,5), R(r,6), R(r,13), R(r,12));
    end
    fclose(fid);
    fprintf('Wrote %s\n', csv);

    csv_b = fullfile(results_dir, 'key_sensitivity_bits_gray.csv');
    fid = fopen(csv_b, 'w');
    fprintf(fid, 'K,flipped_key_bit,npcr_key,uaci_key,psnr_cipher_pair_db\n');
    for r = 1:size(B, 1)
        fprintf(fid, '%d,%d,%.6f,%.6f,%.4f\n', B(r,1), B(r,2), B(r,3), B(r,4), B(r,5));
    end
    fclose(fid);
    fprintf('Wrote %s\n', csv_b);

    [npcr_ideal, uaci_ideal] = npcr_uaci_ideal(8);
    fh = new_figure(13.5, 8.6);
    tl = tiledlayout(fh, 2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

    ax = nexttile(tl);
    plot_metric_vs_K(ax, R(:,1), R(:,3), K_VALUES, npcr_ideal, ...
        'NPCR between the two ciphers (%)', 'one flipped key bit');
    ax = nexttile(tl);
    plot_metric_vs_K(ax, R(:,1), R(:,4), K_VALUES, uaci_ideal, ...
        'UACI between the two ciphers (%)', 'one flipped key bit');

    ax = nexttile(tl);
    plot_metric_vs_K(ax, R(:,1), R(:,6), K_VALUES, NaN, ...
        'PSNR, plain vs wrong-key decryption (dB)', 'lower is better');

    ax = nexttile(tl);
    hold(ax, 'on'); style_axes(ax);
    scatter(ax, B(:,1), B(:,3), 14, [0.62 0.62 0.60], 'filled', ...
        'MarkerFaceAlpha', 0.55, 'MarkerEdgeColor', 'none', ...
        'DisplayName', 'each flipped bit position');
    km = arrayfun(@(K) mean(B(B(:,1) == K, 3)), K_VALUES);
    plot(ax, K_VALUES, km, '-o', 'Color', [0.165 0.471 0.839], 'LineWidth', 2, ...
        'MarkerSize', 5.5, 'MarkerFaceColor', [0.165 0.471 0.839], ...
        'MarkerEdgeColor', 'none', 'DisplayName', 'mean over bit positions');
    yline(ax, npcr_ideal, '--', 'ideal', 'Color', [0.35 0.35 0.35], ...
        'LineWidth', 1, 'FontSize', 10, 'HandleVisibility', 'off');
    xlim(ax, [6 402]); xticks(ax, [24 48:48:384]);
    xlabel(ax, 'K (state bits)'); ylabel(ax, 'NPCR (%)');
    title(ax, 'By flipped bit position (single image)', ...
        'FontWeight', 'normal', 'FontSize', 12.5);
    lg = legend(ax, 'Location', 'southeast'); lg.Box = 'off'; lg.FontSize = 10;

    if all(same_per_K)
        verdict = 'confirmed at every K';
    else
        verdict = sprintf('HOLDS AT ONLY %d OF %d K', sum(same_per_K), numel(K_VALUES));
    end
    layout_title(tl, {'Key sensitivity: grayscale, all SIPI grayscale images', ...
        sprintf(['one flipped key bit \\bullet K = 24:24:384 \\bullet ' ...
                 'ciphertext difference image-independent: %s'], verdict)});
    export_pdf(fh, fullfile(results_dir, 'key_sensitivity_gray.pdf'));
end

function write_histogram(results_dir, R, names, vols, task_img, K_VALUES, files)
    csv = fullfile(results_dir, 'histogram_analysis_gray.csv');
    fid = fopen(csv, 'w');
    fprintf(fid, ['image,volume,K,num_pixels,chi2_plain,chi2_cipher,' ...
        'chi2_critical_005,cipher_uniform_pass\n']);
    for r = 1:size(R, 1)
        fprintf(fid, '%s,%s,%d,%d,%.4f,%.4f,%.4f,%d\n', ...
            names{task_img(r)}, vols{task_img(r)}, R(r,1), R(r,2), ...
            R(r,7), R(r,8), R(r,9), R(r,8) <= R(r,9));
    end
    fclose(fid);
    fprintf('Wrote %s\n', csv);

    pass_rate = 100 * mean(R(:,8) <= R(:,9));
    fprintf('Cipher histograms passing chi-square at alpha=0.05: %.1f%%\n', pass_rate);

    fh = new_figure(13.5, 8.6);
    tl = tiledlayout(fh, 2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

    % chi-square of the cipher vs K
    ax = nexttile(tl);
    plot_metric_vs_K(ax, R(:,1), R(:,8), K_VALUES, R(1,9), ...
        'Cipher \chi^2 (255 dof)', 'dashed = 5% critical value');

    % plain vs cipher chi-square, log scale -- they differ by ~4 decades
    ax = nexttile(tl);
    hold(ax, 'on'); style_axes(ax);
    histogram(ax, log10(max(R(:,7), 1)), 40, 'FaceColor', [0.922 0.408 0.204], ...
        'EdgeColor', 'none', 'FaceAlpha', 0.75, 'DisplayName', 'plain');
    histogram(ax, log10(max(R(:,8), 1)), 40, 'FaceColor', [0.165 0.471 0.839], ...
        'EdgeColor', 'none', 'FaceAlpha', 0.75, 'DisplayName', 'cipher');
    xline(ax, log10(R(1,9)), '--', '5% critical', 'Color', [0.35 0.35 0.35], ...
        'LineWidth', 1, 'FontSize', 10, 'HandleVisibility', 'off');
    xlabel(ax, 'log_{10} \chi^2'); ylabel(ax, 'count');
    title(ax, 'Plain vs cipher \chi^2', 'FontWeight', 'normal', 'FontSize', 12.5);
    lg = legend(ax, 'Location', 'north'); lg.Box = 'off'; lg.FontSize = 10;

    % example histograms, plain and cipher, for one image at the top K
    plain = imread(files{1});
    K = K_VALUES(end);
    cipher = xormap_image_encrypt_fast(plain, secret_key(K));

    ax = nexttile(tl);
    draw_histogram(ax, plain, [0.922 0.408 0.204], ...
        sprintf('Plain histogram (%s)', short_name(files{1})));
    ax = nexttile(tl);
    draw_histogram(ax, cipher, [0.165 0.471 0.839], ...
        sprintf('Cipher histogram (same image, K=%d)', K));

    layout_title(tl, {'Histogram analysis: grayscale, all SIPI grayscale images', ...
        sprintf(['\\chi^2 uniformity over 256 levels \\bullet ' ...
                 'cipher passes at \\alpha=0.05 in %.1f%% of (image, K) cases'], pass_rate)});
    export_pdf(fh, fullfile(results_dir, 'histogram_analysis_gray.pdf'));
end

function write_psnr(results_dir, R, names, vols, task_img, K_VALUES)
    csv = fullfile(results_dir, 'psnr_analysis_gray.csv');
    fid = fopen(csv, 'w');
    fprintf(fid, ['image,volume,K,num_pixels,psnr_plain_cipher_db,' ...
        'psnr_plain_wrongkey_db,psnr_roundtrip_db\n']);
    for r = 1:size(R, 1)
        fprintf(fid, '%s,%s,%d,%d,%.4f,%.4f,%s\n', ...
            names{task_img(r)}, vols{task_img(r)}, R(r,1), R(r,2), ...
            R(r,10), R(r,6), fmt_inf(R(r,11)));
    end
    fclose(fid);
    fprintf('Wrote %s\n', csv);

    n_inf = sum(isinf(R(:,11)));
    fprintf('Round-trip PSNR is +Inf (exact recovery) in %d of %d cases.\n', ...
        n_inf, size(R, 1));

    fh = new_figure(13.5, 5.4);
    tl = tiledlayout(fh, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

    ax = nexttile(tl);
    plot_metric_vs_K(ax, R(:,1), R(:,10), K_VALUES, NaN, ...
        'PSNR, plain vs cipher (dB)', 'lower is better');
    ax = nexttile(tl);
    plot_metric_vs_K(ax, R(:,1), R(:,6), K_VALUES, NaN, ...
        'PSNR, plain vs wrong-key decryption (dB)', 'lower is better');

    layout_title(tl, {'PSNR: grayscale, all SIPI grayscale images', ...
        sprintf(['low = plaintext not recoverable \\bullet round-trip PSNR is ' ...
                 '+Inf in %d/%d cases (XOR is lossless)'], n_inf, size(R,1))});
    export_pdf(fh, fullfile(results_dir, 'psnr_analysis_gray.pdf'));
end

% --- shared plotting -------------------------------------------------------

function plot_metric_vs_K(ax, k, v, K_VALUES, ideal, ylab, note)
    hold(ax, 'on'); style_axes(ax);
    finite = isfinite(v);
    scatter(ax, k(finite), v(finite), 9, [0.62 0.62 0.60], 'filled', ...
        'MarkerFaceAlpha', 0.25, 'MarkerEdgeColor', 'none');
    m = arrayfun(@(K) mean(v(k == K & finite)), K_VALUES);
    plot(ax, K_VALUES, m, '-o', 'Color', [0.165 0.471 0.839], 'LineWidth', 2, ...
        'MarkerSize', 5.5, 'MarkerFaceColor', [0.165 0.471 0.839], 'MarkerEdgeColor', 'none');
    if ~isnan(ideal)
        yline(ax, ideal, '--', 'ideal', 'Color', [0.35 0.35 0.35], ...
            'LineWidth', 1, 'FontSize', 10, 'LabelHorizontalAlignment', 'right');
    end
    xlim(ax, [6 402]); xticks(ax, [24 48:48:384]);
    xlabel(ax, 'K (state bits)'); ylabel(ax, ylab);
    title(ax, note, 'FontWeight', 'normal', 'FontSize', 12.5);
end

function draw_histogram(ax, img, colour, ttl)
    hold(ax, 'on'); style_axes(ax);
    counts = histcounts(double(img(:)), -0.5:1:255.5);
    bar(ax, 0:255, counts, 1, 'FaceColor', colour, 'EdgeColor', 'none');
    yline(ax, numel(img) / 256, '--', 'flat', 'Color', [0.35 0.35 0.35], ...
        'LineWidth', 1, 'FontSize', 10);
    xlim(ax, [-2 257]);
    xlabel(ax, 'grey level'); ylabel(ax, 'count');
    title(ax, ttl, 'FontWeight', 'normal', 'FontSize', 12.5);
end

function s = short_name(path)
    [~, s] = fileparts(path);
    s = strrep(s, '_', '\_');
end

function s = fmt_inf(v)
    if isinf(v)
        s = 'Inf';
    else
        s = sprintf('%.4f', v);
    end
end

function start_pool()
    n = feature('numcores');
    pool = gcp('nocreate');
    if isempty(pool) || pool.NumWorkers ~= n
        if ~isempty(pool)
            delete(pool);
        end
        c = parcluster('local');
        if c.NumWorkers < n
            c.NumWorkers = n;
            saveProfile(c);
        end
        pool = parpool('local', n);
    end
    fprintf('Using parallel pool with %d workers.\n', pool.NumWorkers);
end

function fh = new_figure(w, h)
    fh = figure('Visible', 'off', 'Units', 'inches', 'Position', [1 1 w h], 'Color', 'w');
    try %#ok<TRYNC>
        theme(fh, 'light');
    end
    set(fh, 'Color', 'w');
end

function style_axes(ax)
    ax.FontSize = 11.5; ax.LineWidth = 0.9; ax.Box = 'off'; ax.TickDir = 'out';
    ax.XColor = [0.043 0.043 0.043]; ax.YColor = [0.043 0.043 0.043];
    ax.GridAlpha = 0.12; grid(ax, 'on');
end

function layout_title(tl, lines)
    title(tl, lines{1}, 'FontSize', 15, 'FontWeight', 'bold', 'Color', [0.043 0.043 0.043]);
    if numel(lines) > 1
        subtitle(tl, lines{2}, 'FontSize', 11, 'Color', [0.32 0.32 0.32]);
    end
end

function export_pdf(fh, path)
% Vector PDF only: this repo produces no raster output.
    exportgraphics(fh, path, 'ContentType', 'vector', 'BackgroundColor', 'white');
    close(fh);
    fprintf('Wrote %s\n', path);
end

function [files, names, vols] = read_manifest(manifest_path, img_dir)
    fid = fopen(manifest_path);
    header = strsplit(fgetl(fid), ',');
    fcol = find(strcmp(header, 'filename'));
    ncol = find(strcmp(header, 'name'));
    vcol = find(strcmp(header, 'volume'));
    files = {}; names = {}; vols = {};
    while ~feof(fid)
        line = fgetl(fid);
        if isempty(line)
            continue;
        end
        parts = strsplit(line, ',');
        files{end + 1} = fullfile(img_dir, parts{fcol}); %#ok<AGROW>
        names{end + 1} = parts{ncol}; %#ok<AGROW>
        vols{end + 1} = parts{vcol}; %#ok<AGROW>
    end
    fclose(fid);
end
